name: PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  phpcs:
    name: PHPCS

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1.2.0
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
