name: "PHPStan"

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  static-analysis:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Select PHP 8.1
        run: sudo update-alternatives --set php /usr/bin/php8.1

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run static analysis with phpstan
        run: ./vendor/bin/phpstan analyze --configuration=phpstan.neon
