name: "PHPUnit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  phpunit:
    name: "PHPUnit Tests"
    runs-on: ubuntu-latest
    services:
      integrations-db:
        image: mysql:5.7
        ports:
          - '8888:3306'
        env:
          MYSQL_USER: integrations
          MYSQL_PASSWORD: integrations
          MYSQL_DATABASE: integrations_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Set PHP 8.1
      run: sudo update-alternatives --set php /usr/bin/php8.1

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp ci/env .env

    - name: Install Dependencies
      run: composer install --no-scripts

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Generate key
      run: php artisan key:generate

    - name: Generate passport encryption keys
      run: php artisan passport:keys

    - name: Run migrations
      run: php artisan migrate

    # TESTS
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit

